# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

FACEBOOK_APP_ID: "436592866423465"
FACEBOOK_SECRET_KEY: "d8e0bf02966a46740a7674d947d3d8e7"
GMAIL_PASSWORD: 'starterleague'
GMAIL_USERNAME: 'nagitive'

# FACEBOOK_APP_TOKEN ='436592866423465|M35GBwF47W2-xLEVys-n-tyeSws'

production:
  FACEBOOK_APP_ID: "224676817673489"
  FACEBOOK_SECRET_KEY: "dee566d81462e87246a361ef7be382a3"
  GMAIL_PASSWORD: 'starterleague'
  GMAIL_USERNAME: 'nagitive'
# Will's original localhost app values
# FACEBOOK_APP_ID: "521194684598530"
# FACEBOOK_SECRET_KEY: "a58fbed7c39dc194038dab093c81e7ae"
